name: Vivliostyle build in Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file Dockerfile --tag my-image
    - run: docker run --rm -v "$(pwd)":/app my-image npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: book
        path: dist/output.pdf
